### ISSUE TITLE
How do you make a curved line?

### ISSUE THREAD

**Issue by valkyrienyanko** [ValksGodotTools/ProceduralArt#1]
I want to make a curved trunk like this.

![Untitled](https://user-images.githubusercontent.com/6277739/235383895-b43440b0-5a8a-4850-9ea4-33e8abe13b37.png)

```cs
private void Trunk()
{
    for (int x = 0; x < 5; x++)
    {
        for (int y = 0; y < 40; y++)
        {
            SetPixel(x, y, darkBrown);
        }
    }
}
```
So far I'm just drawing a rectangular trunk.

**Comment by Staslend** [comment]
What about Bezier curves? I have already made some functions for drawing and generating them. The result looks weird and looks like old wire from under the bed, but I think smoothness controls will fix that. Below is my code. I am working with WPF so I do it this way. I'm kind of a noob here, so if there's a better solution, I'll gladly jump to it.

```
        //One dimentional Bezier curve function for 4 points
        double P(double t, double A, double B, double C, double D)
        {
            return ((Math.Pow(1.0-t, 3) * A) + 
                    3 * t * (Math.Pow(1.0 - t, 2)) * B + 
                    3 * Math.Pow(t, 2) * (1 - t) * C +
                    Math.Pow(t, 3) * D);
        }

        //Drawing of Bezier curve from points positions 
        // A - starting point | D - end point 
        public void DrawBazileCurve(double ax, double ay, double dx, double dy, double bx, double by, double cx, double cy)
        {
            for(double t = 0; t <= 1; t += 0.001)
            {
                int Px = (int)P(t, ax, bx, cx, dx);
                int Py = (int)P(t, ay, by, cy, dy);
                SetPixel(Px, Py);
            }
        }

        //Two functions below are for curve generation.
        ///It is not a final result, I just played with them a little to see result 
        public void GenerateBazileCurve(int startX, int startY, int deviH, int deviW)
        {
            Random random = new Random();

            int endX = startX + random.Next(-deviW, deviW);
            int endY = startY + random.Next(-deviH, deviH);

            DrawBazileCurve(startX, startY,
                            endX , endY,
                            startX + random.Next(-deviW, deviW), startY + (endY - startY) / 3,
                            startX + random.Next(-deviW, deviW), startY + ((endY - startY) / 3 * 2));
        }

        //Recursive function, iteration variable represent the number of curves that should go one after another
        public void GenerateBazileCurve(int startX, int startY, int deviH, int deviW, int iteration)
        {
            Random random = new Random();

            int endX = startX + random.Next(-deviW, deviW);
            int endY = startY + random.Next(0, deviH);

            DrawBazileCurve(startX, startY,
                            endX, endY,
                            startX + random.Next(0, deviW), startY + (endY - startY) / 3,
                            startX + random.Next(-deviW, 0), startY + ((endY - startY) / 3 * 2));


            if(iteration > 0) GenerateBazileCurve(endX, endY, deviH, deviW / 2, iteration-1);
        }

```

**Comment by valkyrienyanko** [comment]
I just remembered that Godot has Bezier paths built in. That is, the `Path2D` node has them. Then the `PathFollow2D` node can be used to get all the points on the path. Actually I don't even need `PathFollow2D` because `Path2D` has [`Curve2D.GetBakedPoints()`](https://docs.godotengine.org/en/stable/classes/class_curve2d.html#class-curve2d-method-get-baked-points).

So I can make the trunk with one curve. Then make a bunch of other curves branch off from that trunk. This seems a lot more do-able now!

Might be a little tricky to do all this through code. [Here is a reference to how I generated them in script before](https://github.com/ValksGodotTools/GodotUtils/blob/10b9ee82eeff64ab2a5d4089a2cfcab772a2fbf1/Scripts/Godot%20Helpers/GPath.cs#L118-L140). And [here you can see that code being used to generate the lines for a map.](https://user-images.githubusercontent.com/6277739/230230962-5be85090-b6fb-48bd-bd10-8926ce09a231.mp4)

https://user-images.githubusercontent.com/6277739/235528874-4588e183-ff49-4e53-93e5-96bb8e001a9d.mp4

**Comment by valkyrienyanko** [comment]
I tested it out 91707471479f8a38b769d1cf667cbd4d4fcd90c8

![Untitled](https://user-images.githubusercontent.com/6277739/235559383-65d10cfd-c861-4180-b076-32ba8a0a9c49.png)

But I'm not sure how to fill in the gaps between each point.
```cs
private void Trunk()
{
    var points = GetNode<Path2D>("Path2D").Curve.GetBakedPoints();

    for (int i = 0; i < points.Length - 1; i++)
    {
        var pointA = points[i];
        var pointB = points[i + 1];

        for (int a = 0; a < pointA.DistanceTo(pointB); a++)
        {
            // ?
        }

        SetPixel((int)pointA.X, (int)pointA.Y, darkBrown);
    }
}
```

**Comment by Staslend** [comment]
I checked the [documentation ](https://docs.godotengine.org/en/stable/classes/class_curve2d.html )and there are two properties in Curve2D class that are responsible for points number and interval between them. Did you tried to change them?

**Comment by valkyrienyanko** [comment]
Oh I never knew that was a thing. Goes to show how important reading the entire documentation for what it is you're having trouble with is so important. I will definitely try this out tomorrow but right now it's getting late. Thank you for this, very much appreciated. 👍

**Comment by valkyrienyanko** [comment]
![Untitled](https://user-images.githubusercontent.com/6277739/235756444-95145c09-afc5-4f43-9278-504d6854fb8f.png)

```cs
private void Trunk()
{
    var curve = GetNode<Path2D>("Path2D").Curve;
    curve.BakeInterval = 1;
    var points = curve.GetBakedPoints();

    for (int i = 0; i < points.Length - 1; i++)
    {
        var pointA = points[i];

        for (int w = 0; w < 2; w++)
        {
            SetPixel(pointA.X + w, pointA.Y, Utils.Color(75, 65, 49));
        }

        for (int w = 2; w < 10; w++)
        {
            SetPixel(pointA.X + w, pointA.Y, Utils.Color(55, 48, 36));
        }
    }
}
```

Thank you, setting the bake interval of the curve to 1 did it.
